### ISSUE TITLE
Saved Briefs

### ISSUE THREAD

**Issue by cuteolaf** [ImbueNetwork/imbue-frontend#119]
- [x] Implement `Save` button on the brief details page
![image](https://github.com/ImbueNetwork/imbue-frontend/assets/53915161/38d5587c-aac7-4e2d-9bfe-b15473998d08)
   - [x] Create a new table for saved briefs
   - [x] Create API endpoint to save a brief
   - [x] Create API endpoint to list saved briefs
- [x] Show list of saved briefs on the briefs page.
![image](https://github.com/ImbueNetwork/imbue-frontend/assets/53915161/20d29e4a-fa84-4c47-9629-8685359f52f0)

**Comment by vadik0101** [comment]
pr link: https://github.com/ImbueNetwork/imbue-frontend/pull/131
