### ISSUE TITLE
Need better error messages

### ISSUE THREAD

**Issue by ssani7** [ImbueNetwork/imbue-frontend#173]
while making transaction in submit brief and start work functions, there error messages are not easy to understand

![image](https://github.com/ImbueNetwork/imbue-frontend/assets/66258879/cf96d928-26cd-4fae-83f5-171d8d6a4e3c)

**Comment by Adityaakr** [comment]
can i work on this?

**Comment by ssani7** [comment]
> can i work on this?

Thank you for your interest @Adityaakr . But this issue is solved already. Closing it now
